### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by sergio-nunez-meneses** [bus-stop/terminus#153]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [terminus](https://github.com/bus-stop/terminus) package 4.0.6

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:177

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at Task.send (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:43629)
    at Task.start (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:43461)
    at Function.Task.once (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:14:42559)
    at TerminusView.forkPtyProcess (/packages/terminus/lib/view.js:156:17)
    at TerminusView.displayTerminal (/packages/terminus/lib/view.js:168:28)
    at /packages/terminus/lib/view.js:294:14
    at /packages/terminus/lib/view.js:649:7)
    at HTMLDivElement.fn (/packages/jade-autocompile/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/jade-autocompile/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/jade-autocompile/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:22.5.0 core:paste (input.hidden-input)
     -2:21.8.0 editor:newline (input.hidden-input)
     -2:17.4.0 intentions:highlight (input.hidden-input)
     -2:17.2.0 core:save (input.hidden-input)
     -2:09.3.0 intentions:highlight (input.hidden-input)
     -2:09.1.0 editor:select-to-end-of-word (input.hidden-input)
     -2:08.6.0 core:backspace (input.hidden-input)
     -2:08.3.0 intentions:highlight (input.hidden-input)
     -2:08.2.0 core:save (input.hidden-input)
     -0:38.5.0 editor:newline (input.hidden-input)
     -0:38.4.0 intentions:highlight (input.hidden-input)
     -0:38.4.0 core:paste (input.hidden-input)
     -0:37.2.0 core:move-down (input.hidden-input)
     -0:17.2.0 terminus:new (input.hidden-input)
     -0:03.7.0 intentions:highlight (input.hidden-input)
     -0:03.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-bracket-highlight 0.3.2 
atom-brackets-glow 0.6.0 
atom-clock 0.1.18 
atom-file-icons 0.7.1 
atom-ide-debugger-react-native 0.7.3 
atom-ide-ui 0.13.0 
atom-jade 0.3.0 
atom-less 0.1.10 
atom-material-syntax 1.0.8 
atom-pug 0.2.0 
atom-python-run 0.9.7 
atom-react 0.4.0 
atom-react-native-style 0.2.0 
atom-symfony 1.2.4 
atom-symfony-snippets 0.2.1 
atom-symfony2 0.3.0 
atom-twig 4.2.0 
autocompile-less 1.0.1 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
file-icons 2.1.42 
file-type-icons 1.3.4 
ide-python 1.5.0 
intentions 1.1.5 
jade 1.2.0 
jade-autocompile 0.8.5 
jade-beautify 0.1.5 
kite 0.196.0 
language-pug 0.0.22 
language-pug-jade 0.2.1 
language-twig 1.6.4 
less-autocompile 1.0.0 
linter 2.3.1 
linter-less 2.6.0 
linter-pug 2.0.14 
linter-pug-lint 0.2.0 
linter-twig 0.4.2 
linter-ui-default 1.8.1 
nuclide-format-js 0.0.47 
nuclide-test-runner-cmd 0.1.0 
php-twig 4.0.0 
pigments 0.40.2 
pug 0.8.0 
python-debugger 0.2.0 
python-indent 1.2.6 
python-tools 0.6.9 
react-native-components 0.1.1 
react-native-debug-style 0.1.0 
react-native-snippets 0.3.0 
react-redux-react-native-snippets 0.2.4 
react-snippets 1.2.0 
snippets-jade 0.3.0 
symfony-commands 0.4.3 
symfony-snippets 0.3.0 
terminus 4.0.6 
trailing-spaces 0.4.0 
vue-pug-coffee-stylus-snippets 0.0.7 
```

**Comment by the-j0k3r** [comment]
Uninstall and reinstall terminus while Atom is turned off.

These are caused by bad upgrades, which is APM domain.

**Comment by sergio-nunez-meneses** [comment]
Thank you !
I actually ended up closing and reopening Atom, and terminus is back again.
