### ISSUE TITLE
Failed to activate the terminus package

### ISSUE THREAD

**Issue by Aerospace-Briefcase** [bus-stop/terminus#170]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [terminus](https://github.com/bus-stop/terminus) package 4.0.6

### Stack Trace

Failed to activate the terminus package

```
At Cannot find module 'atom-space-pen-views'
Require stack:
- C:\Users\User\.atom\packages\terminus-master\lib\status-bar.js
- C:\Users\User\.atom\packages\terminus-master\lib\terminus.js
- C:\Users\User\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html

Error: Cannot find module 'atom-space-pen-views'
Require stack:
- C:\Users\User\.atom\packages\terminus-master\lib\status-bar.js
- C:\Users\User\.atom\packages\terminus-master\lib\terminus.js
- C:\Users\User\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/terminus-master/lib/status-bar.js:2:21)
    at /packages/terminus-master/lib/status-bar.js:616:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at Object.consumeStatusBar (/packages/terminus-master/lib/terminus.js:14:31)
    at Provider.provide (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:1107022)
    at ServiceHub.consume (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3694735)
    at Package.activateServices (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3703020)
    at Package.activateNow (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3699775)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1190051)
    at Emitter.emit (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:1191492)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:383966)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:382717
```

### Commands

```
```

### Non-Core Packages

```
script 3.26.0 
terminus 4.0.6 
```

**Comment by the-j0k3r** [comment]
Bad install or upgrade, blame apm/node-gyp, =(

1. Close Atom (all instances)
1. Remove `./atom/packages/terminus`
1. run on an external terminal `apm install terminus`
1. Open Atom profit

Cant do anything to fix the issues are many and outside our control. Best solution on any failure is rinse and repeat steaps above, if persists make sure you purge old apm/npm caches for good measure.

It works otherwise in all OS's with sane Atom installs

**Comment by the-j0k3r** [comment]
Closing no response.
