### ISSUE TITLE
Installation issues - Uncaught Error

### ISSUE THREAD

**Issue by waseem253** [bus-stop/terminus#196]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [terminus](https://github.com/bus-stop/terminus) package 4.1.2

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\ENVY\.atom\packages\terminus\lib\process.js'
Require stack:
- C:\Users\ENVY\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module 'C:\Users\ENVY\.atom\packages\terminus\lib\process.js'
Require stack:
- C:\Users\ENVY\AppData\Local\atom\app-1.54.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Function.resolve (internal/modules/cjs/helpers.js:21:19)
    at Function.customRequire.resolve (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:5112251)
    at new Task (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:41575)
    at Function.Task.once (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:42482)
    at TerminusView.forkPtyProcess (/packages/terminus/lib/view.js:156:17)
    at TerminusView.displayTerminal (/packages/terminus/lib/view.js:168:28)
    at /packages/terminus/lib/view.js:294:14
    at /packages/terminus/lib/view.js:649:7)
    at HTMLDivElement.fn (/packages/vk-terminal/node_modules/jquery/dist/jquery.js:4855:19)
    at HTMLDivElement.dispatch (/packages/vk-terminal/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/vk-terminal/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:31.6.0 core:backspace (input.hidden-input)
     -3:05.2.0 core:confirm (input.hidden-input)
     -2:48.7.0 core:backspace (input.hidden-input)
     -2:46.6.0 core:paste (div.placeholder-text)
```

### Non-Core Packages

```
atom-django 0.3.2 
atom-win-term 0.4.1 
terminus 4.1.2 
vk-terminal 3.0.1 
```

**Comment by the-j0k3r** [comment]
Bad install or upgrade, blame apm/node-gyp, =)

1. Close Atom (all instances)
1. Remove `~/.atom/packages/terminus`
1. run on an external terminal `apm install terminus`
1. Open Atom profit

Best solution on any failure and nonsense errors is rinse and repeat steps above, if persists make sure you purge old apm/npm caches for good measure.

It works otherwise in all OS's with sane Atom installs

**Comment by the-j0k3r** [comment]
Also I suggest you remove vk-terminal its an outdated terminal no longer works or is supported.

**Comment by waseem253** [comment]
@the-j0k3r  thank you.

**Comment by the-j0k3r** [comment]
Let me know what the result is. ;)

**Comment by the-j0k3r** [comment]
So it works right?

**Comment by waseem253** [comment]
@the-j0k3r  yes
