### ISSUE TITLE
Uncaught TypeError: dataTransfer.files.forEach is not a function

### ISSUE THREAD

**Issue by ThatXliner** [bus-stop/terminus#230]
[Enter steps to reproduce:]

1. open terminus
2. Drag a file from `Finder` to the open terminus window

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.2.1
**Thrown From**: [terminus](https://github.com/bus-stop/terminus) package 4.1.3

### Stack Trace

Uncaught TypeError: dataTransfer.files.forEach is not a function

```
At /Users/bryanhu/.atom/packages/terminus/lib/view.js:150

TypeError: dataTransfer.files.forEach is not a function
    at TerminusView.recieveItemOrFile (/packages/terminus/lib/view.js:150:28)
    at HTMLDivElement.dispatch (/packages/script/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/script/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:38.4.0 tree-view:remove (div.tool-panel.tree-view)
     -3:29.9.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -3:29.6.0 core:backspace (input.hidden-input)
     -3:29 core:save (input.hidden-input)
     -3:18.5.0 find-and-replace:select-next (input.hidden-input)
     -3:15.3.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -3:15 core:backspace (input.hidden-input)
     -3:13.4.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -3:13.2.0 core:backspace (input.hidden-input)
     -3:12.8.0 core:save (input.hidden-input)
     -3:09.1.0 core:move-left (input.hidden-input)
     -3:08.6.0 core:save (input.hidden-input)
  2x -2:09.5.0 core:close (input.hidden-input)
     -1:37.4.0 terminus:toggle (input.hidden-input)
     -0:49 key-binding-resolver:toggle (input.hidden-input)
  3x -0:48 terminus:toggle (atom-pane.pane)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-discord 2.0.2 
atom-ide-base 2.6.0 
atom-ide-datatip 0.24.1 
atom-ide-definitions 0.4.1 
atom-ide-hyperclick 1.0.10 
atom-ide-javascript 1.5.0 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 2.3.4 
atom-ide-signature-help 0.15.3 
atom-jinja2 0.6.0 
atom-typescript 14.2.1 
atomic-monokai-pro-syntax 1.2.6 
autocomplete-paths 2.15.2 
busy-signal 2.0.1 
clone-cursor 1.1.2 
docblock-python 0.19.1 
emmet 2.4.3 
emoji-code 0.11.1 
emoji-syntax 1.7.6 
fall-syntax 2.5.0 
file-icons 2.1.47 
gitmoji-atom 0.2.0 
hey-pane 1.2.0 
highlight-selected 0.17.0 
ide-python 1.8.0 
intentions 1.1.5 
javascript-drag-import 0.1.13 
kite 0.204.0 
language-diff 0.7.0 
language-grammars 1.1.0 
language-restructuredtext 1.1.2 
language-v 1.1.0 
linter 3.3.1 
linter-eslint 8.6.6 
linter-mypy 2.6.11 
linter-pylint 2.1.1 
linter-ui-default 3.3.1 
MagicPython 1.1.1 
markdown-preview-enhanced 0.18.11 
minimap 4.39.14 
minimap-linter 2.2.2 
multi-cursor 3.0.0 
pigments 0.40.6 
poe-run 0.0.0 
quick-issues 0.9.3 
script 3.31.1 
soft-wrap-indicator 1.1.0 
split-diff 1.6.1 
Sublime-Style-Column-Selection 1.7.5 
TabNine 3.0.3 
terminus 4.1.3 
trailing-spaces 0.4.0 
```

**Comment by UziTech** [comment]
Looks like `dataTransfer.files` is a [FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) not an array.

**Comment by ThatXliner** [comment]
Can confirm that the latest release fixed this
