### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by zkcao** [bus-stop/terminus#287]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.6
**Thrown From**: [terminus](https://github.com/bus-stop/terminus) package 4.1.5

### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /Users/caozhenkun/.atom/packages/terminus/node_modules/term.js/src/term.js:1939

TypeError: Cannot set property '0' of undefined
    at Terminal.write (/packages/terminus/node_modules/term.js/src/term.js:1939:55)
    at /packages/terminus/lib/view.js:187:21
    at /private/var/folders/gh/x_gd1mj96gb4tw8491lz_7040000gn/T/AppTranslocation/530398A2-5FC6-49F3-ABD1-E5BE249D9F2B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:43955
    at Function.simpleDispatch (/private/var/folders/gh/x_gd1mj96gb4tw8491lz_7040000gn/T/AppTranslocation/530398A2-5FC6-49F3-ABD1-E5BE249D9F2B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (/private/var/folders/gh/x_gd1mj96gb4tw8491lz_7040000gn/T/AppTranslocation/530398A2-5FC6-49F3-ABD1-E5BE249D9F2B/d/Atom.app/Contents/Resources/app/static/<embedded>:11:1187631)
    at ChildProcess.<anonymous> (/private/var/folders/gh/x_gd1mj96gb4tw8491lz_7040000gn/T/AppTranslocation/530398A2-5FC6-49F3-ABD1-E5BE249D9F2B/d/Atom.app/Contents/Resources/app/static/<embedded>:14:43068)
    at ChildProcess.emit (events.js:223:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.47 
ide-r 0.1.8 
language-r 0.4.2 
terminus 4.1.5 
```

**Comment by the-j0k3r** [comment]
Hello @zkcao 

This is due to a bad upgrade or bad install of the terminal

1. Close Atom (all instances)
1. Remove `~/.atom/packages/terminus`
1. run on an external terminal `apm install terminus`
1. Open Atom profit

It works otherwise in all OS's with sane Atom installs

let me know how that worked for you.

**Comment by the-j0k3r** [comment]
No reply, closing as its invalid anyway.
